---
- name: K8s | add repository key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: K8s | add repository
  apt_repository:
    # NOTE: there are currently no binaries for Debian Stretch armhf
    #repo: deb http://apt.kubernetes.io/ kubernetes-{{ansible_distribution_release}} main
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    update_cache: yes
    state: present

- name: K8s | install packages
  apt:
    name: "{{ item }}"
    state: latest
  loop:
  - kubeadm
  - kubectl
  - kubelet

- name: K8s | pin the version of kubelet
  command: apt-mark hold kubelet

- name: K8s | disable kubelet fail-on-swap
  lineinfile:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: '^Environment="KUBELET_EXTRA_ARGS='
    insertbefore: '^ExecStart=$'
    line: 'Environment="KUBELET_EXTRA_ARGS=--fail-swap-on=false"'
    state: present
  # Disable, it is done in kubeadm config
  when: false