---
- name: restart system
  shell: shutdown -r +1 'Ansible Reboot triggered'
  async: 0
  poll: 0
  failed_when: false
  when: ansible_connection != "local"

- name: wait for system restart
  wait_for_connection:
    delay: 10
    timeout: 600