---
work_directory: /tmp/ansible/kubeadm
kubeadm_config: "{{ work_directory }}/kubeadm_config.yaml"
node_name: "{{ ansible_hostname }}"
cluster_name: kubernetes
apiserver_fqdn: "{{ ansible_fqdn }}"
apiserver_ipv4: "{{ ansible_default_ipv4.address }}"
apiserver_port: 6443
certs_dir: /etc/kubernetes/pki