---
- name: Ensure work directory exists
  file:
    name: "{{ work_directory }}"
    state: directory
    mode: 0770

- include_tasks: init.yml
  args:
    apply:
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

- include_tasks: networking_weave.yml
  args:
    apply:
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

- include_tasks: kubectl_user.yml
