---
- name: Fail2Ban | install package
  apt:
    name: fail2ban
    state: present
    update_cache: yes

- name: Fail2Ban | ensure service is running
  service:
    name: fail2ban
    enabled: yes
    state: started
